version: '3.6'

services:
  gate:
    build: ./
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    env_file:
      - .env
#    environment:
#      BASE_COIN: ${BASE_COIN}
#      NODE_API: ${NODE_API}
#      NODE_API_TIMEOUT: ${NODE_API_TIMEOUT}
#      GATE_DEBUG: ${GATE_DEBUG}
#      GATE_PORT: ${GATE_PORT}
