apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-methods: "POST, OPTIONS, PUT, GET, HEAD"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,TE,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    nginx.ingress.kubernetes.io/proxy-body-size: 15m
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  rules:
    - host: "{{ .Values.ingress.domain }}"
      http:
        paths:
          - backend:
              serviceName: "{{ include "chart.fullname" . }}"
              servicePort: {{ .Values.service.port }}
            path: /
  tls:
    - hosts:
        - "{{ .Values.ingress.domain }}"
      secretName: {{ include "chart.fullname" . }}
