name: MainNet

on:
   push:
     branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Version
        uses: pCYSl5EDgo/cat@master
        id: version
        with:
          path: VERSION
          trim: true

      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        env:
          USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          IMAGE_NAME: "minterteam/explorer-gate"
          DOCKERFILE: ".docker/gate/Dockerfile"
          LATEST: "true"
          VERSION: "${{ steps.version.outputs.text }}"
          TAG_NAME: ${{ github.sha }}
          DOCKER_BUILD_ARGS: --build-arg VERSION=${{ steps.version.outputs.text }}

      - name: Deploy
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_PROD_CONFIG_DATA }}
          TAG_NAME: ${{ github.sha }}
        with:
          args: helm upgrade gate chart/ --reuse-values --atomic --timeout 100s --set image.tag=$TAG_NAME -n mainnet

      - name: notification
        if: cancelled() == false
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.TELEGRAM_CI_TOKEN }}
          chatId: ${{ secrets.TELEGRAM_CI_PROD_TO }}
          jobStatus: ${{ job.status }}
          skipSuccess: false
